# Windows testing using Visual Studio.

# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx

# shallow_clone: true

cache:
  - simbody

install:

  # Use Chocolatey to install SWIG 3.0.0.
  #- cinst swig
  #- dir
  
  # Put MSBuild on the path.
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - ps: Get-Content -Path OpenSim/Common/Test/TRCFileWithNANs.trc
  
  # Simbody.
  # Download.
  #- git clone https://github.com/simbody/simbody.git --depth 1 --branch master C:/simbody-src
  #- cd C:/simbody-src
  # Configure.
  #- cmake . -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_VISUALIZER=OFF -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/simbody"
  # Build and install. Pass MSBuild commands after the --
  #- cmake --build . --target install --config Release -- /maxcpucount /verbosity:quiet

build_script:

  # Configure and build OpenSim.
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake . -DSIMBODY_HOME=%APPVEYOR_BUILD_FOLDER%/simbody
  - MSBuild OpenSim.sln /target:ALL_BUILD /p:Configuration=Release /maxcpucount /verbosity:quiet

test_script:
  - dir
  - echo %APPVEYOR_BUILD_FOLDER%
  - MSBuild RUN_TESTS.vcxproj /p:Configuration=Release
  #- cmake --build . --target RUN_TESTS --config Release
  #- MSBuild OpenSim.sln /target:RUN_TESTS /p:Configuration=Release /maxcpucount # /verbosity:quiet
  #ctest -j8 -C "Release" --output-on-failure
