# Windows testing using Visual Studio.

# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx

shallow_clone: true

install:

  # Use Chocolatey to install SWIG 3.0.0.
  - cinst swig
  
  # Put MSBuild on the path.
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  
  # Simbody: download, configure, build, test, install.
  - git clone https://github.com/simbody/simbody.git --depth 1 --branch master C:/simbody-src
  - cd C:/simbody-src
  - cmake . -DBUILD_EXAMPLES=OFF -DBUILD_VISUALIZER=OFF -DCMAKE_INSTALL_PREFIX=C:/simbody
  - MSBuild Simbody.sln /maxcpucount /target:ALL_BUILD /p:Configuration=Release /verbosity:minimal
  - ctest -j8 -C "Release"
  - MSBuild Simbody.sln /target:INSTALL /p:Configuration=Release /verbosity:minimal

build_script:

  # Configure and build OpenSim.
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake . -DSIMBODY_HOME=C:/simbody
  - MSBuild OpenSim.sln /maxcpucount /target:ALL_BUILD /p:Configuration=Release

test_script:
  - ctest -j8 -C "Release" --output-on-failure
