# Windows testing using Visual Studio.

# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

shallow_clone: true

install:

  # Use Chocolatey to install SWIG 3.0.0.
  - cinst swig
  
  # Put MSBuild on the path.
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  
  # Simbody: download, configure, build, test, install.
  - git clone https://github.com/simbody/simbody.git --depth 1 --branch master C:/simbody-src
  - cd C:/simbody-src
  - cmake . -DBUILD_EXAMPLES=OFF -DBUILD_VISUALIZER=OFF -DCMAKE_INSTALL_PREFIX=C:/simbody
  - MSBuild Simbody.sln /maxcpucount /target:ALL_BUILD /p:Configuration=Release
  - ctest -j8 -C "Release"
  - MSBuild Simbody.sln /target:INSTALL /p:Configuration=Release

build_script:

  # Configure and build OpenSim.
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake . -DSIMBODY_HOME=C:/simbody
  - MSBuild OpenSim.sln /maxcpucount /target:ALL_BUILD /p:Configuration=Release

test_script:
  - ctest -j8 -C "Release" --output-on-failure
